# En este notebook se incluyen fragmentos de código con datos de prueba 

## Eliminar nombres similares

In [ ]:
import difflib

word = "learning"
possibilities = ["love", "learn", "lean", "moving", "hearing"]
n = 3
cutoff = 0.2

close_matches = difflib.get_close_matches(word, 
                possibilities, n, cutoff)

print(close_matches)

In [ ]:
list_name = ['Alberto','Juan','Pedro','Pedros','Albert','Pepe','Jose','x','x','x','ola','hola','Albertiño']
new_list_name = []

n = 4
sensibility = 0

for i in list(range(len(list_name))):
    
    word = list_name[i]
    possibilities = list_name[(i+1):]
    
    close_matches = difflib.get_close_matches(word, possibilities, n, 1-sensibility)
    
    if len(close_matches) == 0:
        new_list_name.append(list_name[i])
new_list_name

In [ ]:
list_name = ['Alberto','Juan','Pedro','Pedros','Albert','Pepe','Jose','x','x','x','ola','hola','Albertiño']
new_list_name = []
dup_list_name = []

n = 4
sensibility = 0.5

for i in list(range(len(list_name))):
    
    word = list_name[i]
    possibilities = list_name[(i+1):]
    
    close_matches = difflib.get_close_matches(word, possibilities, n, 1-sensibility)
    
    if len(close_matches) == 0:
        new_list_name.append(list_name[i])
    else:
        dup_list_name.append(list_name[i])
new_list_name

In [ ]:
dup_list_name

In [ ]:
import pandas as pd

pd.DataFrame(new_list_name).reset_index()

In [ ]:
pd.DataFrame(list_name).reset_index()

In [ ]:
pd.merge(pd.DataFrame(list_name),pd.DataFrame(new_list_name),on=index,how='inner')

In [ ]:
list_name = df_ue_t1.iloc[0:11]['Name']
new_list_name = []

n = 4
sensibility = 0.1

for i in list(range(len(list_name))):
    
    word = list_name[i]
    possibilities = list_name[(i+1):]
    
    close_matches = difflib.get_close_matches(word, possibilities, n, 1-sensibility)
    
    if len(close_matches) == 0:
        new_list_name.append(list_name[i])
new_list_name

In [ ]:
list_name = df_ue_t1.iloc[0:11]['Name']
list_name

## Traductor

In [ ]:
df_eeuu = pd.read_csv('datos_entrada_script_02/df_eeuu.csv').iloc[:,1:]
df_prueba = df_eeuu_t1.head(4)

for i in df_prueba.index:
    for j in df_prueba.columns:
        trans = Translator().translate(df_prueba.loc[i,j] , dest ='es').text 
        print(trans)

In [ ]:
string = "Zurich CH-8022"

new_string = re.sub(r"(, .{0,50})|( [A-Z]{0,16}-[0-9]{0,50})|( \w\w\d.{0,50}[0-9]{0,50})","", string)
new_string

## Agrupar por ID

In [ ]:
import pandas as pd
df = pd.DataFrame(columns=['id','nombre'])
df = df.append({'id': 0, 'nombre':'Clarae'}, ignore_index=True)
df = df.append({'id': 0, 'nombre':'Halegarth'}, ignore_index=True)
df = df.append({'id': 1, 'nombre':'yon'}, ignore_index=True)
df = df.append({'id': 1, 'nombre':'juan'}, ignore_index=True)
df = df.append({'id': 1, 'nombre':'pedro'}, ignore_index=True)
df = df.append({'id': 2, 'nombre':'Halegarth'}, ignore_index=True)

array=df.groupby(['id'])['nombre'].transform(lambda x : ';'.join(x)).unique()
len(array)

## Modelo ML No Supervisado

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from category_encoders import BinaryEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

prueba = pd.DataFrame()
prueba['col1']=['a','b','a','a',np.nan]
prueba['col2']=[np.nan,'b','b','a',np.nan]

In [3]:
encoder = Pipeline([
                    ("binary",BinaryEncoder(handle_missing='return_nan'))
                    
])

encoder.fit_transform(prueba)

col1_0  col1_1  col2_0  col2_1
0     0.0     1.0     NaN     NaN
1     1.0     0.0     1.0     0.0
2     0.0     1.0     1.0     0.0
3     0.0     1.0     1.0     1.0
4     NaN     NaN     NaN     NaN

In [4]:
simple_imputer = Pipeline([
                         ("binary",BinaryEncoder(handle_missing='return_nan')), 
                         ('imputer',SimpleImputer(strategy='constant',fill_value=0))
])

simple_imputer.fit_transform(prueba)

array([[0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 1.],
       [0., 0., 0., 0.]])

In [13]:
pca = Pipeline([
                ("binary",BinaryEncoder(handle_missing='return_nan')), 
                ('imputer',SimpleImputer(strategy='constant',fill_value=0)),
                ('pca',PCA(n_components=0.85))
])

pca.fit_transform(prueba)

array([[ 0.13459368, -0.69606513,  0.19773752],
       [-0.7666076 ,  0.77159415,  0.06813571],
       [ 0.39060608,  0.12220851,  0.43019191],
       [ 0.84979107,  0.3546629 , -0.38808173],
       [-0.60838324, -0.55240042, -0.3079834 ]])

In [7]:
standard_scaler = Pipeline([
                ("binary",BinaryEncoder(handle_missing='return_nan')), 
                ('imputer',SimpleImputer(strategy='constant',fill_value=0)),
                ('pca',PCA(n_components=0.85)),
                ('std',StandardScaler())
])

standard_scaler.fit_transform(prueba)

array([[ 0.22123174, -1.26007351,  0.64203952],
       [-1.26007351,  1.39680225,  0.22123174],
       [ 0.64203952,  0.22123174,  1.39680225],
       [ 1.39680225,  0.64203952, -1.26007351],
       [-1.        , -1.        , -1.        ]])

In [ ]:
kmeans = Pipeline([
                ("binary",BinaryEncoder(handle_missing='return_nan')), 
                ('imputer',SimpleImputer(strategy='constant',fill_value=0)),
                ('pca',PCA(n_components=0.85)),
                ('std',StandardScaler()),
                ()

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder
from category_encoders import BinaryEncoder
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline

In [1]:
prueba = pd.DataFrame()
prueba['col1']=['a','b','a','a',np.nan]
prueba['col2']=[np.nan,'b','b','a',np.nan]
prueba['col3']=['c','b','b','a','d']
prueba['col4']=['d','b','b','a','a']
prueba

NameError: name 'pd' is not defined

In [12]:

ct = ColumnTransformer([
                        ('ordinal',OrdinalEncoder(),['col3']),
                        
])

pd.DataFrame(ct.fit_transform(prueba))

0
0  2.0
1  1.0
2  1.0
3  0.0
4  3.0

In [17]:
ct = ColumnTransformer([
                        ('ordinal',OrdinalEncoder(encoded_missing_value=nan),['col1']), # Valor por defecto de encoded_missing_value es nan
                        ('binary',BinaryEncoder(handle_missing='return_nan'),['col2','col3'])
])

pd.DataFrame(ct.fit_transform(prueba))

0    1    2    3    4    5
0  0.0  NaN  NaN  0.0  0.0  1.0
1  1.0  1.0  0.0  0.0  1.0  0.0
2  0.0  1.0  0.0  0.0  1.0  0.0
3  0.0  1.0  1.0  0.0  1.0  1.0
4  NaN  NaN  NaN  1.0  0.0  0.0

In [25]:


encoder_name = Pipeline([
                        ('oe',OrdinalEncoder(encoded_missing_value=np.nan)),
                        ('ms',MinMaxScaler(feature_range=(-0.001,0.001)))
                         
    
])


ct = ColumnTransformer([
                        ('ordinal_encoder',encoder_name,['col1']), # Valor por defecto de encoded_missing_value es nan
                        ('binary',BinaryEncoder(handle_missing='return_nan'),['col2','col3'])
])

pd.DataFrame(ct.fit_transform(prueba))

0    1    2    3    4    5
0 -0.001  NaN  NaN  0.0  0.0  1.0
1  0.001  1.0  0.0  0.0  1.0  0.0
2 -0.001  1.0  0.0  0.0  1.0  0.0
3 -0.001  1.0  1.0  0.0  1.0  1.0
4    NaN  NaN  NaN  1.0  0.0  0.0

In [23]:
encoder_name = Pipeline([
                        ('oe',OrdinalEncoder(encoded_missing_value=np.nan),
                         #MinMaxScaler(feature_range=(-0.001,0.001))
                         
    
]).fit_transform(prueba)

TypeError: cannot unpack non-iterable OrdinalEncoder object

In [12]:
from sklearn.preprocessing import OrdinalEncoder, MinMaxScaler, OneHotEncoder
import numpy as np

onehot = OneHotEncoder(handle_unknown='infrequent_if_exist')

onehot.fit_transform(prueba).toarray()

array([[1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 1.]])

In [4]:
prueba

col1 col2
0    a  NaN
1    b    b
2    a    b
3    a    a
4  NaN  NaN

In [38]:
import matplotlib.pyplot as plt
from sklearn.decomposition import MiniBatchSparsePCA, KernelPCA, PCA

encoder = OneHotEncoder(sparse=False) # Codifica los nulos como filas de ceros


PCA = Pipeline([
                ('encoder',encoder),
                ('PCA',PCA(random_state=10))
])

PCA.fit(prueba)
PCA.transform(prueba)

array([[ 6.01500955e-01,  2.87954789e-01, -4.65920636e-01,
        -3.71748034e-01, -1.28858939e-17],
       [-9.73248989e-01, -7.53875426e-01,  1.77965847e-01,
        -2.29752921e-01,  4.26252574e-17],
       [-6.01500955e-01,  2.87954789e-01, -4.65920636e-01,
         3.71748034e-01, -1.23908196e-16],
       [-1.54546378e-15,  9.31841273e-01,  5.75909579e-01,
        -4.02528055e-16,  7.03808330e-17],
       [ 9.73248989e-01, -7.53875426e-01,  1.77965847e-01,
         2.29752921e-01,  4.26252574e-17]])

In [37]:
import matplotlib.pyplot as plt
from sklearn.decomposition import MiniBatchSparsePCA, KernelPCA, PCA

encoder = OneHotEncoder(sparse=False) # Codifica los nulos como filas de ceros
encoded = encoder.fit_transform(prueba)

PCA = PCA(n_components=5)
PCA.fit_transform(encoded) # NO se puede hacer pipeline si se quiere aplicar explained_variance_ratio

print('Variance of each component:', PCA.explained_variance_ratio_)
print('\n Total Variance Explained:', round(sum(list(PCA.explained_variance_ratio_))*100, 2))

Variance of each component: [4.36338998e-01 3.61803399e-01 1.38196601e-01 6.36610019e-02
 6.02406180e-35]

 Total Variance Explained: 100.0


In [39]:
prueba

col1 col2
0    a  NaN
1    b    b
2    a    b
3    a    a
4  NaN  NaN

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder, MinMaxScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from category_encoders import BinaryEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, silhouette_samples
import matplotlib.cm as cm
import matplotlib.pyplot as plt
from sklearn.decomposition import MiniBatchSparsePCA, KernelPCA

sanctionlist = pd.read_csv('datos_entrada_script_04_y_PowerBI/sanctionlist.csv').iloc[:,1:]

ml_ns = sanctionlist[sanctionlist['Origin']=='EEUU'].drop(columns=
                                                          ['Address','Origin'],errors=
                                                          'ignore').drop_duplicates().reset_index(drop=True)


In [2]:
len(ml_ns)

12890

In [8]:
len(ml_ns.drop_duplicates())

12890

In [12]:
si = SimpleImputer(strategy='constant',fill_value=0)
si_transform = si.fit_transform(ml_ns)
si.fit_transform(ml_ns).shape

(12890, 4)

In [15]:
pd.DataFrame(si_transform).drop_duplicates()

0           1               2            3
0         AEROCARIBBEAN AIRLINES  ENTERPRISE            CUBA       HAVANA
1      ANGLO-CARIBBEAN CO., LTD.  ENTERPRISE  UNITED KINGDOM       LONDON
2         BANCO NACIONAL DE CUBA  ENTERPRISE     SWITZERLAND       ZURICH
3         BANCO NACIONAL DE CUBA  ENTERPRISE           SPAIN       MADRID
4         BANCO NACIONAL DE CUBA  ENTERPRISE           JAPAN        TOKYO
...                          ...         ...             ...          ...
12885              GLORY HARVEST      VESSEL               0            0
12886               TORNADO CASH  ENTERPRISE               0            0
12887              TWEHWAY, BILL  INDIVIDUAL         LIBERIA     MONROVIA
12888     CEPHUS, SAYMA SYRENIUS  INDIVIDUAL         LIBERIA            0
12889          MCGILL, NATHANIEL  INDIVIDUAL         LIBERIA  PAYNESVILLE

[12890 rows x 4 columns]

In [4]:
encoder_name = Pipeline([
                        ('oe',OrdinalEncoder(encoded_missing_value=np.nan)), # Valor por defecto de encoded_missing_value es nan
                        ('ms',MinMaxScaler(feature_range=(-1e-4,1e-4))) #Por defecto deja los valores nulos como np.nan
                         
    
])
#print(encoder_name.fit(ml_ns))

encoder = ColumnTransformer([
                            ('encoder_name',encoder_name,['Name']),
                            ('binary',BinaryEncoder(handle_missing='return_nan'),['EntityType','Country','City'])
])

In [8]:
pd.DataFrame(encoder.fit_transform(ml_ns)).drop_duplicates()

0    1    2    3    4    5    6    7    8    9   ...   14   15  \
0     -0.000096  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     -0.000079  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     -0.000071  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
3     -0.000071  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
4     -0.000071  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
...         ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
12885 -0.000030  0.0  1.0  1.0  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
12886  0.000083  0.0  0.0  1.0  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
12887  0.000085  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  ...  1.0  1.0   
12888 -0.000060  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  ...  NaN  NaN   
12889  0.000021  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  ...  0.0  0.0   

        16   17   18   19   20   21   22   23  
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
1      0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
2      0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  
3      0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  
4      0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
...    ...  ...  ...  ...  ...  ...  ...  ...  
12885  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
12886  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
12887  0.0  1.0  1.0  0.0  1.0  1.0  0.0  1.0  
12888  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
12889  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  

[12890 rows x 24 columns]